version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GCP_PROJECT_ID=dummy_for_now
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devleap
      - POSTGRES_PASSWORD=devleap
      - POSTGRES_DB=devleap_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
